# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/march/School/gl_tutorials

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/march/School/gl_tutorials

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/march/School/gl_tutorials/CMakeFiles /home/march/School/gl_tutorials//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/march/School/gl_tutorials/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named 01_triangle_vanilla

# Build rule for target.
01_triangle_vanilla: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 01_triangle_vanilla
.PHONY : 01_triangle_vanilla

# fast build rule for target.
01_triangle_vanilla/fast:
	$(MAKE) $(MAKESILENT) -f 01_triangle/CMakeFiles/01_triangle_vanilla.dir/build.make 01_triangle/CMakeFiles/01_triangle_vanilla.dir/build
.PHONY : 01_triangle_vanilla/fast

#=============================================================================
# Target rules for targets named 01_triangle

# Build rule for target.
01_triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 01_triangle
.PHONY : 01_triangle

# fast build rule for target.
01_triangle/fast:
	$(MAKE) $(MAKESILENT) -f 01_triangle/CMakeFiles/01_triangle.dir/build.make 01_triangle/CMakeFiles/01_triangle.dir/build
.PHONY : 01_triangle/fast

#=============================================================================
# Target rules for targets named 02_simple3d

# Build rule for target.
02_simple3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 02_simple3d
.PHONY : 02_simple3d

# fast build rule for target.
02_simple3d/fast:
	$(MAKE) $(MAKESILENT) -f 02_simple3d/CMakeFiles/02_simple3d.dir/build.make 02_simple3d/CMakeFiles/02_simple3d.dir/build
.PHONY : 02_simple3d/fast

#=============================================================================
# Target rules for targets named 03_textures

# Build rule for target.
03_textures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 03_textures
.PHONY : 03_textures

# fast build rule for target.
03_textures/fast:
	$(MAKE) $(MAKESILENT) -f 03_textures/CMakeFiles/03_textures.dir/build.make 03_textures/CMakeFiles/03_textures.dir/build
.PHONY : 03_textures/fast

#=============================================================================
# Target rules for targets named 04_deffered

# Build rule for target.
04_deffered: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 04_deffered
.PHONY : 04_deffered

# fast build rule for target.
04_deffered/fast:
	$(MAKE) $(MAKESILENT) -f 04_deffered/CMakeFiles/04_deffered.dir/build.make 04_deffered/CMakeFiles/04_deffered.dir/build
.PHONY : 04_deffered/fast

#=============================================================================
# Target rules for targets named 05_shaders

# Build rule for target.
05_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 05_shaders
.PHONY : 05_shaders

# fast build rule for target.
05_shaders/fast:
	$(MAKE) $(MAKESILENT) -f 05_shaders/CMakeFiles/05_shaders.dir/build.make 05_shaders/CMakeFiles/05_shaders.dir/build
.PHONY : 05_shaders/fast

#=============================================================================
# Target rules for targets named 06_noise

# Build rule for target.
06_noise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 06_noise
.PHONY : 06_noise

# fast build rule for target.
06_noise/fast:
	$(MAKE) $(MAKESILENT) -f 06_noise/CMakeFiles/06_noise.dir/build.make 06_noise/CMakeFiles/06_noise.dir/build
.PHONY : 06_noise/fast

#=============================================================================
# Target rules for targets named 07_3d_textures

# Build rule for target.
07_3d_textures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 07_3d_textures
.PHONY : 07_3d_textures

# fast build rule for target.
07_3d_textures/fast:
	$(MAKE) $(MAKESILENT) -f 07_3d_textures/CMakeFiles/07_3d_textures.dir/build.make 07_3d_textures/CMakeFiles/07_3d_textures.dir/build
.PHONY : 07_3d_textures/fast

utils/obj_file_loading.o: utils/obj_file_loading.cpp.o
.PHONY : utils/obj_file_loading.o

# target to build an object file
utils/obj_file_loading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/obj_file_loading.cpp.o
.PHONY : utils/obj_file_loading.cpp.o

utils/obj_file_loading.i: utils/obj_file_loading.cpp.i
.PHONY : utils/obj_file_loading.i

# target to preprocess a source file
utils/obj_file_loading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/obj_file_loading.cpp.i
.PHONY : utils/obj_file_loading.cpp.i

utils/obj_file_loading.s: utils/obj_file_loading.cpp.s
.PHONY : utils/obj_file_loading.s

# target to generate assembly for a file
utils/obj_file_loading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/obj_file_loading.cpp.s
.PHONY : utils/obj_file_loading.cpp.s

utils/ogl_geometry_construction.o: utils/ogl_geometry_construction.cpp.o
.PHONY : utils/ogl_geometry_construction.o

# target to build an object file
utils/ogl_geometry_construction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_construction.cpp.o
.PHONY : utils/ogl_geometry_construction.cpp.o

utils/ogl_geometry_construction.i: utils/ogl_geometry_construction.cpp.i
.PHONY : utils/ogl_geometry_construction.i

# target to preprocess a source file
utils/ogl_geometry_construction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_construction.cpp.i
.PHONY : utils/ogl_geometry_construction.cpp.i

utils/ogl_geometry_construction.s: utils/ogl_geometry_construction.cpp.s
.PHONY : utils/ogl_geometry_construction.s

# target to generate assembly for a file
utils/ogl_geometry_construction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_construction.cpp.s
.PHONY : utils/ogl_geometry_construction.cpp.s

utils/ogl_geometry_factory.o: utils/ogl_geometry_factory.cpp.o
.PHONY : utils/ogl_geometry_factory.o

# target to build an object file
utils/ogl_geometry_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_factory.cpp.o
.PHONY : utils/ogl_geometry_factory.cpp.o

utils/ogl_geometry_factory.i: utils/ogl_geometry_factory.cpp.i
.PHONY : utils/ogl_geometry_factory.i

# target to preprocess a source file
utils/ogl_geometry_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_factory.cpp.i
.PHONY : utils/ogl_geometry_factory.cpp.i

utils/ogl_geometry_factory.s: utils/ogl_geometry_factory.cpp.s
.PHONY : utils/ogl_geometry_factory.s

# target to generate assembly for a file
utils/ogl_geometry_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_geometry_factory.cpp.s
.PHONY : utils/ogl_geometry_factory.cpp.s

utils/ogl_material_factory.o: utils/ogl_material_factory.cpp.o
.PHONY : utils/ogl_material_factory.o

# target to build an object file
utils/ogl_material_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_material_factory.cpp.o
.PHONY : utils/ogl_material_factory.cpp.o

utils/ogl_material_factory.i: utils/ogl_material_factory.cpp.i
.PHONY : utils/ogl_material_factory.i

# target to preprocess a source file
utils/ogl_material_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_material_factory.cpp.i
.PHONY : utils/ogl_material_factory.cpp.i

utils/ogl_material_factory.s: utils/ogl_material_factory.cpp.s
.PHONY : utils/ogl_material_factory.s

# target to generate assembly for a file
utils/ogl_material_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/utils/ogl_material_factory.cpp.s
.PHONY : utils/ogl_material_factory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 01_triangle"
	@echo "... 01_triangle_vanilla"
	@echo "... 02_simple3d"
	@echo "... 03_textures"
	@echo "... 04_deffered"
	@echo "... 05_shaders"
	@echo "... 06_noise"
	@echo "... 07_3d_textures"
	@echo "... utils"
	@echo "... utils/obj_file_loading.o"
	@echo "... utils/obj_file_loading.i"
	@echo "... utils/obj_file_loading.s"
	@echo "... utils/ogl_geometry_construction.o"
	@echo "... utils/ogl_geometry_construction.i"
	@echo "... utils/ogl_geometry_construction.s"
	@echo "... utils/ogl_geometry_factory.o"
	@echo "... utils/ogl_geometry_factory.i"
	@echo "... utils/ogl_geometry_factory.s"
	@echo "... utils/ogl_material_factory.o"
	@echo "... utils/ogl_material_factory.i"
	@echo "... utils/ogl_material_factory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

